name: Pipeline CI Basico

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar Build
        run: |
          echo "Iniciando o processo de build..."
          echo "Instalando dependências fictícias..."
          sleep 2
          echo "Build concluído!"

      - name: Executar Testes
        run: |
          echo "Rodando a suíte de testes..."
          sleep 2
          echo "✅ Todos os testes passaram com sucesso!"
